In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.get_cmap("Spectral")

In [3]:
df = pd.read_csv("./data/media prediction and its cost.csv")
df

,food_category,food_department,food_family,store_sales(in millions),store_cost(in millions),unit_sales(in millions),promotion_name,sales_country,marital_status,gender,...,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,media_type,cost
0,Breakfast Foods,Frozen Foods,Food,7.36,2.7232,4.0,Bag Stuffers,USA,M,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",126.62
1,Breakfast Foods,Frozen Foods,Food,5.52,2.5944,3.0,Cash Register Lottery,USA,M,M,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",59.86
2,Breakfast Foods,Frozen Foods,Food,3.68,1.3616,2.0,High Roller Savings,USA,S,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,"Daily Paper, Radio",84.16
3,Breakfast Foods,Frozen Foods,Food,3.68,1.1776,2.0,Cash Register Lottery,USA,M,F,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,In-Store Coupon,95.78
4,Breakfast Foods,Frozen Foods,Food,4.08,1.4280,3.0,Double Down Sale,USA,M,M,...,18670.0,5415.0,3610.0,1.0,1.0,1.0,1.0,1.0,Radio,50.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60423,Specialty,Carousel,Non-Consumable,2.76,1.3248,1.0,You Save Days,USA,M,F,...,15321.0,4294.0,2863.0,1.0,0.0,0.0,0.0,0.0,In-Store Coupon,95.25
60424,Specialty,Carousel,Non-Consumable,1.60,0.4960,1.0,Price Cutters,USA,S,F,...,15321.0,4294.0,2863.0,1.0,0.0,0.0,0.0,0.0,Sunday Paper,69.42
60425,Specialty,Carousel,Non-Consumable,5.52,2.5392,2.0,Weekend Markdown,USA,M,M,...,15321.0,4294.0,2863.0,1.0,0.0,0.0,0.0,0.0,"Sunday Paper, Radio, TV",67.51
60426,Specialty,Carousel,Non-Consumable,8.28,2.5668,3.0,Sales Days,Canada,S,M,...,27463.0,4193.0,2795.0,1.0,0.0,0.0,0.0,1.0,Sunday Paper,132.88
60427,Specialty,Carousel,Non-Consumable,9.20,4.2320,4.0,Super Duper Savers,Canada,S,F,...,27463.0,4193.0,2795.0,1.0,0.0,0.0,0.0,1.0,"Daily Paper, Radio",87.76

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60428 entries, 0 to 60427
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   food_category               60428 non-null  object
 1   food_department             60428 non-null  object
 2   food_family                 60428 non-null  object
 3   store_sales(in millions)    60428 non-null  float64
 4   store_cost(in millions)     60428 non-null  float64
 5   unit_sales(in millions)     60428 non-null  float64
 6   promotion_name              60428 non-null  object
 7   sales_country               60428 non-null  object
 8   marital_status              60428 non-null  object
 9   gender                      60428 non-null  object
 10  total_children              60428 non-null  float64
 11  education                   60428 non-null  object
 12  member_card                 60428 non-null  object
 13  occupation                  60428 non-null  object
 14  houseowner                  60428 non-null  object
 15  avg_cars_at home(approx)    60428 non-null  float64
 16  avg. yearly_income          60428 non-null  object
 17  num_children_at_home        60428 non-null  float64
 18  avg_cars_at home(approx).1  60428 non-null  float64
 19  brand_name                  60428 non-null  object
 20  SRP                         60428 non-null  float64
 21  gross_weight                60428 non-null  float64
 22  net_weight                  60428 non-null  float64
 23  recyclable_package          60428 non-null  float64
 24  low_fat                     60428 non-null  float64
 25  units_per_case              60428 non-null  float64
 26  store_type                  60428 non-null  object
 27  store_city                  60428 non-null  object
 28  store_state                 60428 non-null  object
 29  store_sqft                  60428 non-null  float64
 30  grocery_sqft                60428 non-null  float64
 31  frozen_sqft                 60428 non-null  float64
 32  meat_sqft                   60428 non-null  float64
 33  coffee_bar                  60428 non-null  float64
 34  video_store                 60428 non-null  float64
 35  salad_bar                   60428 non-null  float64
 36  prepared_food               60428 non-null  float64
 37  florist                     60428 non-null  float64
 38  media_type                  60428 non-null  object
 39  cost                        60428 non-null  float64
dtypes: float64(23), object(17)
memory usage: 18.4+ MB

In [5]:
df.describe()

,store_sales(in millions),store_cost(in millions),unit_sales(in millions),total_children,avg_cars_at home(approx),num_children_at_home,avg_cars_at home(approx).1,SRP,gross_weight,net_weight,...,store_sqft,grocery_sqft,frozen_sqft,meat_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,cost
count,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,...,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000,60428.000000
mean,6.541031,2.619460,3.093169,2.533875,2.200271,0.829351,2.200271,2.115258,13.806433,11.796289,...,27988.477494,19133.799696,5312.852552,3541.846280,0.612646,0.354157,0.587956,0.587956,0.562603,99.262366
std,3.463047,1.453009,0.827677,1.490165,1.109644,1.303424,1.109644,0.932829,4.622693,4.682986,...,5701.022090,3987.395735,1575.907263,1050.471635,0.487150,0.478261,0.492207,0.492207,0.496069,30.011257
min,0.510000,0.163200,1.000000,0.000000,0.000000,0.000000,0.000000,0.500000,6.000000,3.050000,...,20319.000000,13305.000000,2452.000000,1635.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.790000
25%,3.810000,1.500000,3.000000,1.000000,1.000000,0.000000,1.000000,1.410000,9.700000,7.710000,...,23593.000000,16232.000000,4746.000000,3164.000000,0.000000,0.000000,0.000000,0.000000,0.000000,69.650000
50%,5.940000,2.385600,3.000000,3.000000,2.000000,0.000000,2.000000,2.130000,13.600000,11.600000,...,27694.000000,18670.000000,5062.000000,3375.000000,1.000000,0.000000,1.000000,1.000000,1.000000,98.520000
75%,8.670000,3.484025,4.000000,4.000000,3.000000,1.000000,3.000000,2.790000,17.700000,16.000000,...,30797.000000,22123.000000,5751.000000,3834.000000,1.000000,1.000000,1.000000,1.000000,1.000000,126.620000
max,22.920000,9.726500,6.000000,5.000000,4.000000,5.000000,4.000000,3.980000,21.900000,20.800000,...,39696.000000,30351.000000,9184.000000,6122.000000,1.000000,1.000000,1.000000,1.000000,1.000000,149.750000

In [29]:
cols = list(df.columns)
def col_type(n):
    return df[n].dtype
df['food_category'].dtype
cat_type = list(filter(lambda x:col_type(x) == "O",cols))
cat_type = list(filter(lambda x:col_type(x) == "O",cols))

In [40]:
cat_type

['food_category',
 'food_department',
 'food_family',
 'promotion_name',
 'sales_country',
 'marital_status',
 'gender',
 'education',
 'member_card',
 'occupation',
 'houseowner',
 'avg. yearly_income',
 'brand_name',
 'store_type',
 'store_city',
 'store_state',
 'media_type']

In [ ]:
fig,axes = plt.subplots(17,1)
i = 0
for x in cat_type:
    axes[i].bar(df[x],10)
    i = i + 1 
    print("done")

done
done
done
done